plugins {
    id "java"
    id("io.freefair.lombok") version "9.5.0"
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("com.google.code.gson:gson:2.14.0")
    testImplementation("org.seleniumhq.selenium:selenium-java:4.44.0")
    testImplementation("org.seleniumhq.selenium:selenium-chrome-driver:4.44.0")
    testImplementation(platform("org.junit:junit-bom:6.0.3"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
    useJUnitPlatform()
    testLogging.showStandardStreams = true
}
